# Generated by Django 5.2.6 on 2025-09-09 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('equipment', 'Equipment'), ('uniform', 'Uniform'), ('t-shirt', 'T-Shirt'), ('socks', 'Socks'), ('merchandise', 'Merchandise'), ('other', 'Other')], default='other', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
    ]
