# Generated by Django 5.2.6 on 2025-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.URLField(blank=True, null=True),
        ),
    ]
