# Generated by Django 5.2.6 on 2025-10-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
